blogs/blogs/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('form.urls')),
]

blogs/form/urls.py
from django.conf.urls import include, url
from . import views
app_name='form'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail,name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
##    url(r'^post/(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
   ]

blogs/form/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

# Create your models here.

blogs/form/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

    
class DeleteForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ()

blogs/form/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .forms import PostForm,DeleteForm
from .models import Post
from django.shortcuts import redirect

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'form/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
       
    
## delete post
    form_to_delete = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = DeleteForm(request.POST, instance=form_to_delete)
        if form.is_valid():
            form_to_delete.delete()
          
            return redirect('form:post_list')    
        else:
            form = DeleteForm(instance=form_to_delete)
    
    return render(request,'form/post_detail.html',{'post':post})
    return render(request, 'form/post_detail.html', {'post': post})


    

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
    

    
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('form:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'form/new_post.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('form:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'form/post_edit.html', {'form': form ,'post': post})


##def post_delete(request,pk):
    
    

# Create your views here.

blogs/form/templates/form/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Post something here</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	 
	 
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/form.css' %}">
    </head>
    <body>
        <div class="page-header">
            
	     <a href="{% url 'form:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
	     
            <h1><a href="/">Post something here</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
     <script src="C:/Users/lim/Downloads/bootstrap-3.3.6/bootstrap-3.3.6/docs/dist/js/bootstrap.min.js"></script>
     <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
     <script type="text/javascript" src="{% static 'js/modal.js' %}"></script>
    </body>
</html>

blogs/form/templates/form/new_post.html
{% extends 'form/base.html' %}

{% block content %}
    <h1>New Post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blogs/form/templates/form/post_delete.html
{% extends 'form/base.html' %}

{% block content %}
    deleted
{% endblock %}

blogs/form/templates/form/post_detail.html
{% extends 'form/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
	 	
	
        <a class="btn btn-default" href="{% url 'form:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
	 {% if user.is_authenticated %}
	 <form method="POST" class="post-form">{% csrf_token %}
		<button type="submit" class="save btn btn-default">Delete</button>
	 </form>
	 {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaks }}</p>
    </div>
    
{% endblock %}

blogs/form/templates/form/post_edit.html
{% extends 'form/base.html' %}

{% block content %}
    <h1>{{ post }}</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blogs/form/templates/form/post_list.html
{% extends 'form/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h1><a href="{% url 'form:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
	     
	     
	     <p>{{ post.text|linebreaks }}</p>
        </div>
    {% endfor %}
{% endblock %}